// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  az104Sidebar: [
    {
      type: 'doc',
      id: 'az-104/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'az-104/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'az-104/lab-setup',
      label: 'Lab Setup',
    },
    {
      type: 'doc',
      id: 'az-104/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'doc',
      id: 'az-104/cheat-sheet',
      label: 'Azure CLI Cheat Sheet',
    },
    {
      type: 'category',
      label: 'Identity & Governance (20-25%)',
      items: [{type: 'autogenerated', dirName: 'az-104/01-identity'}],
    },
    {
      type: 'category',
      label: 'Storage (15-20%)',
      items: [{type: 'autogenerated', dirName: 'az-104/02-storage'}],
    },
    {
      type: 'category',
      label: 'Compute (20-25%)',
      items: [{type: 'autogenerated', dirName: 'az-104/03-compute'}],
    },
    {
      type: 'category',
      label: 'Networking (15-20%)',
      items: [{type: 'autogenerated', dirName: 'az-104/04-networking'}],
    },
    {
      type: 'category',
      label: 'Monitor & Maintain (10-15%)',
      items: [{type: 'autogenerated', dirName: 'az-104/05-monitor'}],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{type: 'autogenerated', dirName: 'az-104/06-capstone'}],
    },
    {
      type: 'doc',
      id: 'az-104/coverage-matrix',
      label: 'Coverage Matrix',
    },
    {
      type: 'category',
      label: 'Coach Guide',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'coach'}],
    },
  ],

  az305Sidebar: [
    {
      type: 'doc',
      id: 'az-305/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'az-305/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'az-305/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'category',
      label: 'Identity, Governance & Monitoring (25-30%)',
      items: [{type: 'autogenerated', dirName: 'az-305/01-identity-governance-monitoring'}],
    },
    {
      type: 'category',
      label: 'Data Storage (20-25%)',
      items: [{type: 'autogenerated', dirName: 'az-305/02-data-storage'}],
    },
    {
      type: 'category',
      label: 'Business Continuity (15-20%)',
      items: [{type: 'autogenerated', dirName: 'az-305/03-business-continuity'}],
    },
    {
      type: 'category',
      label: 'Infrastructure Solutions (30-35%)',
      items: [{type: 'autogenerated', dirName: 'az-305/04-infrastructure'}],
    },
    {
      type: 'doc',
      id: 'az-305/coverage-matrix',
      label: 'Coverage Matrix',
    },
  ],
};

export default sidebars;
