// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  az104Sidebar: [
    {
      type: 'doc',
      id: 'az-104/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'az-104/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'az-104/lab-setup',
      label: 'Lab Setup',
    },
    {
      type: 'doc',
      id: 'az-104/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'doc',
      id: 'az-104/cheat-sheet',
      label: 'Azure CLI Cheat Sheet',
    },
    {
      type: 'category',
      label: 'Identity & Governance (20-25%)',
      items: [{type: 'autogenerated', dirName: 'az-104/01-identity'}],
    },
    {
      type: 'category',
      label: 'Storage (15-20%)',
      items: [{type: 'autogenerated', dirName: 'az-104/02-storage'}],
    },
    {
      type: 'category',
      label: 'Compute (20-25%)',
      items: [{type: 'autogenerated', dirName: 'az-104/03-compute'}],
    },
    {
      type: 'category',
      label: 'Networking (15-20%)',
      items: [{type: 'autogenerated', dirName: 'az-104/04-networking'}],
    },
    {
      type: 'category',
      label: 'Monitor & Maintain (10-15%)',
      items: [{type: 'autogenerated', dirName: 'az-104/05-monitor'}],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{type: 'autogenerated', dirName: 'az-104/06-capstone'}],
    },
    {
      type: 'doc',
      id: 'az-104/coverage-matrix',
      label: 'Coverage Matrix',
    },
    {
      type: 'category',
      label: 'Coach Guide',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'coach'}],
    },
  ],

  az305Sidebar: [
    {
      type: 'doc',
      id: 'az-305/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'az-305/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'az-305/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'category',
      label: 'Identity, Governance & Monitoring (25-30%)',
      items: [{type: 'autogenerated', dirName: 'az-305/01-identity-governance-monitoring'}],
    },
    {
      type: 'category',
      label: 'Data Storage (20-25%)',
      items: [{type: 'autogenerated', dirName: 'az-305/02-data-storage'}],
    },
    {
      type: 'category',
      label: 'Business Continuity (15-20%)',
      items: [{type: 'autogenerated', dirName: 'az-305/03-business-continuity'}],
    },
    {
      type: 'category',
      label: 'Infrastructure Solutions (30-35%)',
      items: [{type: 'autogenerated', dirName: 'az-305/04-infrastructure'}],
    },
    {
      type: 'doc',
      id: 'az-305/coverage-matrix',
      label: 'Coverage Matrix',
    },
  ],

  az400Sidebar: [
    {
      type: 'doc',
      id: 'az-400/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'az-400/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'az-400/lab-setup',
      label: 'Lab Setup',
    },
    {
      type: 'doc',
      id: 'az-400/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'category',
      label: 'Processes & Communications (10-15%)',
      items: [{type: 'autogenerated', dirName: 'az-400/01-processes-communications'}],
    },
    {
      type: 'category',
      label: 'Source Control (10-15%)',
      items: [{type: 'autogenerated', dirName: 'az-400/02-source-control'}],
    },
    {
      type: 'category',
      label: 'Package Management',
      items: [{type: 'autogenerated', dirName: 'az-400/03a-package-management'}],
    },
    {
      type: 'category',
      label: 'Testing in Pipelines',
      items: [{type: 'autogenerated', dirName: 'az-400/03b-testing-pipelines'}],
    },
    {
      type: 'category',
      label: 'Pipeline Fundamentals',
      items: [{type: 'autogenerated', dirName: 'az-400/03c-pipeline-fundamentals'}],
    },
    {
      type: 'category',
      label: 'Deployment Strategies',
      items: [{type: 'autogenerated', dirName: 'az-400/03d-deployment-strategies'}],
    },
    {
      type: 'category',
      label: 'Infrastructure as Code',
      items: [{type: 'autogenerated', dirName: 'az-400/03e-infrastructure-as-code'}],
    },
    {
      type: 'category',
      label: 'Pipeline Operations',
      items: [{type: 'autogenerated', dirName: 'az-400/03f-pipeline-operations'}],
    },
    {
      type: 'category',
      label: 'Security & Compliance (10-15%)',
      items: [{type: 'autogenerated', dirName: 'az-400/04-security-compliance'}],
    },
    {
      type: 'category',
      label: 'Instrumentation (5-10%)',
      items: [{type: 'autogenerated', dirName: 'az-400/05-instrumentation'}],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{type: 'autogenerated', dirName: 'az-400/06-capstone'}],
    },
    {
      type: 'doc',
      id: 'az-400/coverage-matrix',
      label: 'Coverage Matrix',
    },
  ],

  az900Sidebar: [
    {
      type: 'doc',
      id: 'az-900/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'az-900/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'az-900/lab-setup',
      label: 'Lab Setup',
    },
    {
      type: 'doc',
      id: 'az-900/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'category',
      label: 'Cloud Concepts (25-30%)',
      items: [{type: 'autogenerated', dirName: 'az-900/01-cloud-concepts'}],
    },
    {
      type: 'category',
      label: 'Azure Architecture & Services (35-40%)',
      items: [{type: 'autogenerated', dirName: 'az-900/02-azure-services'}],
    },
    {
      type: 'category',
      label: 'Management & Governance (30-35%)',
      items: [{type: 'autogenerated', dirName: 'az-900/03-management-governance'}],
    },
    {
      type: 'doc',
      id: 'az-900/coverage-matrix',
      label: 'Coverage Matrix',
    },
  ],

  az700Sidebar: [
    {
      type: 'doc',
      id: 'az-700/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'az-700/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'az-700/lab-setup',
      label: 'Lab Setup',
    },
    {
      type: 'doc',
      id: 'az-700/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'doc',
      id: 'az-700/cheat-sheet',
      label: 'Azure Network CLI Cheat Sheet',
    },
    {
      type: 'category',
      label: 'Core Networking (25-30%)',
      items: [{type: 'autogenerated', dirName: 'az-700/01-core-networking'}],
    },
    {
      type: 'category',
      label: 'Connectivity Services (20-25%)',
      items: [{type: 'autogenerated', dirName: 'az-700/02-connectivity'}],
    },
    {
      type: 'category',
      label: 'Application Delivery (15-20%)',
      items: [{type: 'autogenerated', dirName: 'az-700/03-app-delivery'}],
    },
    {
      type: 'category',
      label: 'Private Access (10-15%)',
      items: [{type: 'autogenerated', dirName: 'az-700/04-private-access'}],
    },
    {
      type: 'category',
      label: 'Network Security (15-20%)',
      items: [{type: 'autogenerated', dirName: 'az-700/05-network-security'}],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{type: 'autogenerated', dirName: 'az-700/06-capstone'}],
    },
    {
      type: 'doc',
      id: 'az-700/coverage-matrix',
      label: 'Coverage Matrix',
    },
  ],

  sc500Sidebar: [
    {
      type: 'doc',
      id: 'sc-500/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'sc-500/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'sc-500/lab-setup',
      label: 'Lab Setup',
    },
    {
      type: 'doc',
      id: 'sc-500/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'category',
      label: 'Identity, Access & Governance (20-25%)',
      items: [{type: 'autogenerated', dirName: 'sc-500/01-identity-access-governance'}],
    },
    {
      type: 'category',
      label: 'Storage, Databases & Networking (25-30%)',
      items: [{type: 'autogenerated', dirName: 'sc-500/02-storage-databases-networking'}],
    },
    {
      type: 'category',
      label: 'Secure Compute (20-25%)',
      items: [{type: 'autogenerated', dirName: 'sc-500/03-secure-compute'}],
    },
    {
      type: 'category',
      label: 'Security Posture & Monitoring (20-25%)',
      items: [{type: 'autogenerated', dirName: 'sc-500/04-security-posture-monitoring'}],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{type: 'autogenerated', dirName: 'sc-500/05-capstone'}],
    },
    {
      type: 'doc',
      id: 'sc-500/coverage-matrix',
      label: 'Coverage Matrix',
    },
  ],

  ai900Sidebar: [
    {
      type: 'doc',
      id: 'ai-900/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'ai-900/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'ai-900/lab-setup',
      label: 'Lab Setup',
    },
    {
      type: 'doc',
      id: 'ai-900/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'doc',
      id: 'ai-900/cheat-sheet',
      label: 'Azure AI Services Cheat Sheet',
    },
    {
      type: 'category',
      label: 'AI Workloads & Responsible AI (15-20%)',
      items: [{type: 'autogenerated', dirName: 'ai-900/01-ai-workloads'}],
    },
    {
      type: 'category',
      label: 'Machine Learning on Azure (15-20%)',
      items: [{type: 'autogenerated', dirName: 'ai-900/02-machine-learning'}],
    },
    {
      type: 'category',
      label: 'Computer Vision on Azure (15-20%)',
      items: [{type: 'autogenerated', dirName: 'ai-900/03-computer-vision'}],
    },
    {
      type: 'category',
      label: 'NLP on Azure (15-20%)',
      items: [{type: 'autogenerated', dirName: 'ai-900/04-nlp'}],
    },
    {
      type: 'category',
      label: 'Generative AI on Azure (20-25%)',
      items: [{type: 'autogenerated', dirName: 'ai-900/05-generative-ai'}],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{type: 'autogenerated', dirName: 'ai-900/06-capstone'}],
    },
    {
      type: 'doc',
      id: 'ai-900/coverage-matrix',
      label: 'Coverage Matrix',
    },
  ],

  ai102Sidebar: [
    {
      type: 'doc',
      id: 'ai-102/overview',
      label: 'Exam Overview',
    },
    {
      type: 'doc',
      id: 'ai-102/self-assessment',
      label: 'Am I Ready?',
    },
    {
      type: 'doc',
      id: 'ai-102/lab-setup',
      label: 'Lab Setup',
    },
    {
      type: 'doc',
      id: 'ai-102/exam-tips',
      label: 'Exam Tips & Strategy',
    },
    {
      type: 'doc',
      id: 'ai-102/cheat-sheet',
      label: 'Azure AI SDK Cheat Sheet',
    },
    {
      type: 'category',
      label: 'Plan & Manage AI Solutions (20-25%)',
      items: [{type: 'autogenerated', dirName: 'ai-102/01-plan-manage'}],
    },
    {
      type: 'category',
      label: 'Generative AI Solutions (15-20%)',
      items: [{type: 'autogenerated', dirName: 'ai-102/02-generative-ai'}],
    },
    {
      type: 'category',
      label: 'Agentic Solutions (5-10%)',
      items: [{type: 'autogenerated', dirName: 'ai-102/03-agentic'}],
    },
    {
      type: 'category',
      label: 'Computer Vision Solutions (10-15%)',
      items: [{type: 'autogenerated', dirName: 'ai-102/04-computer-vision'}],
    },
    {
      type: 'category',
      label: 'NLP Solutions (15-20%)',
      items: [{type: 'autogenerated', dirName: 'ai-102/05-nlp'}],
    },
    {
      type: 'category',
      label: 'Knowledge Mining & Extraction (15-20%)',
      items: [{type: 'autogenerated', dirName: 'ai-102/06-knowledge-mining'}],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{type: 'autogenerated', dirName: 'ai-102/07-capstone'}],
    },
    {
      type: 'doc',
      id: 'ai-102/coverage-matrix',
      label: 'Coverage Matrix',
    },
  ],
};

export default sidebars;
